# Generated by Django 4.0.1 on 2022-01-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='op3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='op4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
